from io import BytesIO
import base64

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from app.validator import validator


class PythonExecutor:
    """
    Executes AI-generated Python code
    inside a restricted environment.
    """

    def __init__(self):

        SAFE_BUILTINS = {
            "len": len,
            "min": min,
            "max": max,
            "sum": sum,
            "abs": abs,
            "round": round,
            "sorted": sorted,
            "enumerate": enumerate,
            "range": range,
            "zip": zip,
            "list": list,
            "dict": dict,
            "set": set,
            "tuple": tuple,
            "int": int,
            "float": float,
            "str": str,
            "bool": bool,
            "isinstance": isinstance,
        }

        self.allowed_globals = {
            "__builtins__": SAFE_BUILTINS,
            "pd": pd,
            "np": np,
            "plt": plt,
        }

    # ----------------------------------------
    # Remove Imports Generated By LLM
    # ----------------------------------------

    def _clean_code(self, code: str) -> str:

        cleaned = []

        for line in code.splitlines():

            stripped = line.strip()

            if stripped.startswith("import "):
                continue

            if stripped.startswith("from "):
                continue

            cleaned.append(line)

        return "\n".join(cleaned)

    # ----------------------------------------
    # Make Any Object JSON Safe
    # ----------------------------------------

    def _make_json_safe(self, obj):

        if obj is None:
            return None

        if isinstance(obj, dict):
            return {
                k: self._make_json_safe(v)
                for k, v in obj.items()
            }

        if isinstance(obj, (list, tuple, set)):
            return [
                self._make_json_safe(v)
                for v in obj
            ]

        if isinstance(obj, pd.Timestamp):
            return obj.isoformat()

        if isinstance(obj, pd.Timedelta):
            return str(obj)

        if isinstance(obj, pd.Index):
            return self._make_json_safe(obj.tolist())

        if isinstance(obj, pd.Categorical):
            return self._make_json_safe(obj.tolist())

        if isinstance(obj, np.ndarray):
            return self._make_json_safe(obj.tolist())

        if isinstance(obj, np.integer):
            return int(obj)

        if isinstance(obj, np.floating):

            if np.isnan(obj) or np.isinf(obj):
                return None

            return float(obj)

        if isinstance(obj, np.bool_):
            return bool(obj)

        if pd.isna(obj):
            return None

        return obj

    # ----------------------------------------
    # Serialize Result
    # ----------------------------------------

    def _serialize_result(self, result):

        if result is None:
            return None

        if isinstance(result, pd.DataFrame):
            return self._make_json_safe(
                result.to_dict(orient="records")
            )

        if isinstance(result, pd.Series):
            return self._make_json_safe(
                result.to_dict()
            )

        return self._make_json_safe(result)

    # ----------------------------------------
    # Main Execute Function
    # ----------------------------------------

    def execute(
        self,
        code: str,
        dataframe: pd.DataFrame
    ):

        validator.validate(code)

        plt.close("all")

        globals_dict = self.allowed_globals.copy()
        globals_dict["df"] = dataframe

        locals_dict = {}

        print("=" * 80)
        print("Generated Python Code:")
        print(code)
        print("=" * 80)

        code = self._clean_code(code)

        print("Cleaned Python Code:")
        print(code)
        print("=" * 80)

        try:

            exec(
                code,
                globals_dict,
                locals_dict
            )

        except Exception as e:

            return {
                "result": f"Python execution error: {str(e)}",
                "chart": None
            }

        print("Result:")
        print(locals_dict.get("result"))
        print("=" * 80)

        chart = self._extract_chart()

        return {
            "result": self._serialize_result(
                locals_dict.get("result")
            ),
            "chart": chart,
        }

    # ----------------------------------------
    # Extract Matplotlib Figure
    # ----------------------------------------

    def _extract_chart(self):

        if not plt.get_fignums():
            return None

        buffer = BytesIO()

        plt.savefig(
            buffer,
            format="png",
            bbox_inches="tight"
        )

        plt.close("all")

        buffer.seek(0)

        return base64.b64encode(
            buffer.read()
        ).decode("utf-8")


executor = PythonExecutor()